project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.md"

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "AI Blog"
  navbar:
    right:
      - cv.qmd
      - icon: github
        href: https://github.com/JCfly3000

format:
  html:
    grid:
      body-width: 900px
      sidebar-width: 100px
      margin-width: 250px

    fontsize: 1.2em
    page-layout: full
    toc: true
    toc-location: right
    toc-depth: 3
    theme:
      light: cosmo
      dark: darkly
    css: styles.css

execute:
  freeze: auto  # Options: true, false, auto

